# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.

import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '../platforms'

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Title label
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(0, 10, 400, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.lbl_title.setFont(font)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")

        # Plain Text label
        self.lbl_plain = QtWidgets.QLabel(self.centralwidget)
        self.lbl_plain.setGeometry(QtCore.QRect(20, 60, 100, 30))
        self.lbl_plain.setObjectName("lbl_plain")

        # Plain Text input
        self.txt_plain_text = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(130, 60, 240, 30))
        self.txt_plain_text.setObjectName("txt_plain_text")

        # Key label
        self.lbl_key = QtWidgets.QLabel(self.centralwidget)
        self.lbl_key.setGeometry(QtCore.QRect(20, 110, 100, 30))
        self.lbl_key.setObjectName("lbl_key")

        # Key input
        self.txt_key = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_key.setGeometry(QtCore.QRect(130, 110, 240, 30))
        self.txt_key.setObjectName("txt_key")

        # Cipher Text label
        self.lbl_cipher = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cipher.setGeometry(QtCore.QRect(20, 160, 100, 30))
        self.lbl_cipher.setObjectName("lbl_cipher")

        # Cipher Text input
        self.txt_cipher_text = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(130, 160, 240, 30))
        self.txt_cipher_text.setObjectName("txt_cipher_text")

        # Encrypt button
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(80, 220, 100, 40))
        self.btn_encrypt.setObjectName("btn_encrypt")

        # Decrypt button
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(220, 220, 100, 40))
        self.btn_decrypt.setObjectName("btn_decrypt")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Caesar Cipher"))
        self.lbl_title.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.lbl_plain.setText(_translate("MainWindow", "Plain Text:"))
        self.lbl_key.setText(_translate("MainWindow", "Key:"))
        self.lbl_cipher.setText(_translate("MainWindow", "Cipher Text:"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
