# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '../platforms'

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1063, 583)

        # txt_Plain
        self.txt_Plain = QtWidgets.QTextEdit(Dialog)
        self.txt_Plain.setGeometry(QtCore.QRect(130, 130, 341, 101))
        self.txt_Plain.setObjectName("txt_Plain")

        # txt_Cipher
        self.txt_Cipher = QtWidgets.QTextEdit(Dialog)
        self.txt_Cipher.setGeometry(QtCore.QRect(130, 280, 341, 121))
        self.txt_Cipher.setObjectName("txt_Cipher")

        # txt_Sign
        self.txt_Sign = QtWidgets.QTextEdit(Dialog)
        self.txt_Sign.setGeometry(QtCore.QRect(640, 280, 371, 121))
        self.txt_Sign.setObjectName("txt_Sign")

        # txt_Info
        self.txt_Info = QtWidgets.QTextEdit(Dialog)
        self.txt_Info.setGeometry(QtCore.QRect(640, 130, 371, 101))
        self.txt_Info.setObjectName("txt_Info")

        # label - Plain text
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 170, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        # label_2 - Cipher text
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 330, 91, 16))
        font2 = QtGui.QFont()
        font2.setPointSize(11)
        font2.setBold(True)
        font2.setWeight(75)
        self.label_2.setFont(font2)
        self.label_2.setObjectName("label_2")

        # label_3 - Info
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(550, 170, 71, 16))
        font3 = QtGui.QFont()
        font3.setPointSize(11)
        font3.setBold(True)
        font3.setWeight(75)
        self.label_3.setFont(font3)
        self.label_3.setObjectName("label_3")

        # label_4 - RSA CIPHER title
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(430, 60, 161, 21))
        font4 = QtGui.QFont()
        font4.setPointSize(18)
        font4.setBold(True)
        font4.setWeight(75)
        self.label_4.setFont(font4)
        self.label_4.setObjectName("label_4")

        # label_5 - Sign
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(550, 340, 91, 16))
        font5 = QtGui.QFont()
        font5.setPointSize(11)
        font5.setBold(True)
        font5.setWeight(75)
        self.label_5.setFont(font5)
        self.label_5.setObjectName("label_5")

        # btn_Ge - Generate Keys
        self.btn_Ge = QtWidgets.QPushButton(Dialog)
        self.btn_Ge.setGeometry(QtCore.QRect(650, 60, 91, 31))
        self.btn_Ge.setObjectName("btn_Ge")

        # btn_En - Encrypt
        self.btn_En = QtWidgets.QPushButton(Dialog)
        self.btn_En.setGeometry(QtCore.QRect(140, 470, 75, 31))
        self.btn_En.setObjectName("btn_En")

        # btn_De - Decrypt
        self.btn_De = QtWidgets.QPushButton(Dialog)
        self.btn_De.setGeometry(QtCore.QRect(340, 470, 75, 31))
        self.btn_De.setObjectName("btn_De")

        # btn_Sign - Sign
        self.btn_Sign = QtWidgets.QPushButton(Dialog)
        self.btn_Sign.setGeometry(QtCore.QRect(700, 470, 75, 31))
        self.btn_Sign.setObjectName("btn_Sign")

        # btn_Ve - Verify
        self.btn_Ve = QtWidgets.QPushButton(Dialog)
        self.btn_Ve.setGeometry(QtCore.QRect(910, 470, 75, 31))
        self.btn_Ve.setObjectName("btn_Ve")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Plain text"))
        self.label_2.setText(_translate("Dialog", "Cipher text"))
        self.label_3.setText(_translate("Dialog", "Info"))
        self.label_4.setText(_translate("Dialog", "RSA CIPHER"))
        self.label_5.setText(_translate("Dialog", "Sign"))
        self.btn_Ge.setText(_translate("Dialog", "Generate Keys"))
        self.btn_En.setText(_translate("Dialog", "Encrypt"))
        self.btn_De.setText(_translate("Dialog", "Decrypt"))
        self.btn_Sign.setText(_translate("Dialog", "Sign"))
        self.btn_Ve.setText(_translate("Dialog", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
